# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bundles/*
  skip_cleanup: true
  on:
    tags: true

install:
  - pip install pylint circuitpython-build-tools

script:
  - pylint adafruit_pca9685.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
  - circuitpython-build-bundles --filename_prefix adafruit-circuitpython-pca9685 --library_location .
